twitter/config/routes.rb
Rails.application.routes.draw do
  resources :zombies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

twitter/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

twitter/app/models/zombie.rb
class Zombie < ApplicationRecord
end

twitter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

twitter/app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
  before_action :set_zombie, only: [:show, :edit, :update, :destroy]

  # GET /zombies
  # GET /zombies.json
  def index
    @zombies = Zombie.all
  end

  # GET /zombies/1
  # GET /zombies/1.json
  def show
  end

  # GET /zombies/new
  def new
    @zombie = Zombie.new
  end

  # GET /zombies/1/edit
  def edit
  end

  # POST /zombies
  # POST /zombies.json
  def create
    @zombie = Zombie.new(zombie_params)

    respond_to do |format|
      if @zombie.save
        format.html { redirect_to @zombie, notice: 'Zombie was successfully created.' }
        format.json { render :show, status: :created, location: @zombie }
      else
        format.html { render :new }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zombies/1
  # PATCH/PUT /zombies/1.json
  def update
    respond_to do |format|
      if @zombie.update(zombie_params)
        format.html { redirect_to @zombie, notice: 'Zombie was successfully updated.' }
        format.json { render :show, status: :ok, location: @zombie }
      else
        format.html { render :edit }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zombies/1
  # DELETE /zombies/1.json
  def destroy
    @zombie.destroy
    respond_to do |format|
      format.html { redirect_to zombies_url, notice: 'Zombie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zombie
      @zombie = Zombie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zombie_params
      params.require(:zombie).permit(:name, :bio, :age, :roting, :salary, :heigth, :premium, :zombification, :lunch, :born)
    end
end

twitter/app/helpers/application_helper.rb
module ApplicationHelper
end

twitter/app/helpers/zombies_helper.rb
module ZombiesHelper
end

twitter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

twitter/app/views/zombies/_form.html.erb
<%= form_for(zombie) do |f| %>
  <% if zombie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(zombie.errors.count, "error") %> prohibited this zombie from being saved:</h2>

      <ul>
      <% zombie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :bio %>
    <%= f.text_area :bio %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>

  <div class="field">
    <%= f.label :roting %>
    <%= f.check_box :roting %>
  </div>

  <div class="field">
    <%= f.label :salary %>
    <%= f.text_field :salary %>
  </div>

  <div class="field">
    <%= f.label :heigth %>
    <%= f.text_field :heigth %>
  </div>

  <div class="field">
    <%= f.label :premium %>
    <%= f.text_field :premium %>
  </div>

  <div class="field">
    <%= f.label :zombification %>
    <%= f.date_select :zombification %>
  </div>

  <div class="field">
    <%= f.label :lunch %>
    <%= f.time_select :lunch %>
  </div>

  <div class="field">
    <%= f.label :born %>
    <%= f.datetime_select :born %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

twitter/app/views/zombies/edit.html.erb
<h1>Editing Zombie</h1>

<%= render 'form', zombie: @zombie %>

<%= link_to 'Show', @zombie %> |
<%= link_to 'Back', zombies_path %>

twitter/app/views/zombies/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Zombies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th>Age</th>
      <th>Roting</th>
      <th>Salary</th>
      <th>Heigth</th>
      <th>Premium</th>
      <th>Zombification</th>
      <th>Lunch</th>
      <th>Born</th>
      <th colspan="3"></th>
      <th>Valjakson</th>
    </tr>
  </thead>

  <tbody>
    <% @zombies.each do |zombie| %>
      <tr>
        <td><%= zombie.name %></td>
        <td><%= zombie.bio %></td>
        <td><%= zombie.age %></td>
        <td><%= zombie.roting %></td>
        <td><%= zombie.salary %></td>
        <td><%= zombie.heigth %></td>
        <td><%= zombie.premium %></td>
        <td><%= zombie.zombification %></td>
        <td><%= zombie.lunch %></td>
        <td><%= zombie.born %></td>
        <td><%= link_to 'Show', zombie %></td>
        <td><%= link_to 'Edit', edit_zombie_path(zombie) %></td>
        <td><%= link_to 'Destroy', zombie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zombie', new_zombie_path %>

twitter/app/views/zombies/new.html.erb
<h1>New Zombie</h1>

<%= render 'form', zombie: @zombie %>

<%= link_to 'Back', zombies_path %>

twitter/app/views/zombies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @zombie.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @zombie.bio %>
</p>

<p>
  <strong>Age:</strong>
  <%= @zombie.age %>
</p>

<p>
  <strong>Roting:</strong>
  <%= @zombie.roting %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @zombie.salary %>
</p>

<p>
  <strong>Heigth:</strong>
  <%= @zombie.heigth %>
</p>

<p>
  <strong>Premium:</strong>
  <%= @zombie.premium %>
</p>

<p>
  <strong>Zombification:</strong>
  <%= @zombie.zombification %>
</p>

<p>
  <strong>Lunch:</strong>
  <%= @zombie.lunch %>
</p>

<p>
  <strong>Born:</strong>
  <%= @zombie.born %>
</p>

<%= link_to 'Edit', edit_zombie_path(@zombie) %> |
<%= link_to 'Back', zombies_path %>